#!/bin/sh
#
# @name Gazebo standard_vtol_with_cam
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=standard_vtol_with_cam}

param set-default SIM_GZ_EN 1
param set-default UXRCE_DDS_DOM_ID 0

param set-default EKF2_HGT_REF 0
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Standard VTOL (multirotor lift + fixed-wing cruise)
param set-default CA_AIRFRAME 2
param set-default CA_ROTOR_COUNT 5
param set-default CA_ROTOR0_PX 0.30
param set-default CA_ROTOR0_PY 0.30
param set-default CA_ROTOR0_KM +0.05
param set-default CA_ROTOR1_PX -0.30
param set-default CA_ROTOR1_PY -0.30
param set-default CA_ROTOR1_KM +0.05
param set-default CA_ROTOR2_PX 0.30
param set-default CA_ROTOR2_PY -0.30
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.30
param set-default CA_ROTOR3_PY 0.30
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_PX -0.50
param set-default CA_ROTOR4_PY 0.00
param set-default CA_ROTOR4_KM +0.05

# Control surfaces
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R 1.00
param set-default CA_SV_CS0_TRQ_P 0.00
param set-default CA_SV_CS0_TRQ_Y 0.00
param set-default CA_SV_CS1_TYPE 1
param set-default CA_SV_CS1_TRQ_R -1.00
param set-default CA_SV_CS1_TRQ_P 0.00
param set-default CA_SV_CS1_TRQ_Y 0.00
param set-default CA_SV_CS2_TYPE 2
param set-default CA_SV_CS2_TRQ_R 0.00
param set-default CA_SV_CS2_TRQ_P 1.00
param set-default CA_SV_CS2_TRQ_Y 0.00
param set-default CA_SV_CS3_TYPE 3
param set-default CA_SV_CS3_TRQ_R 0.00
param set-default CA_SV_CS3_TRQ_P 0.00
param set-default CA_SV_CS3_TRQ_Y 1.00

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

# VTOL transition
param set-default VT_ARSP_TRANS 15.0
param set-default VT_PSHER_RMP 3.0
param set-default VT_F_TRANS_DUR 6.0
param set-default VT_B_TRANS_DUR 4.0

param set-default MPC_THR_HOVER 0.65
