#!/bin/sh
#
# @name Gazebo fixed_wing_basic_with_cam
#
# @type Fixed-wing
#

. ${R}etc/init.d/rc.fw_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=fixed_wing_basic_with_cam}

param set-default SIM_GZ_EN 1
param set-default UXRCE_DDS_DOM_ID 0

param set-default EKF2_HGT_REF 0
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Fixed-wing
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.30
param set-default CA_ROTOR0_PY 0.00
param set-default CA_ROTOR0_KM +0.05

# Control surfaces
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R 1.00
param set-default CA_SV_CS0_TRQ_P 0.00
param set-default CA_SV_CS0_TRQ_Y 0.00
param set-default CA_SV_CS1_TYPE 1
param set-default CA_SV_CS1_TRQ_R -1.00
param set-default CA_SV_CS1_TRQ_P 0.00
param set-default CA_SV_CS1_TRQ_Y 0.00
param set-default CA_SV_CS2_TYPE 2
param set-default CA_SV_CS2_TRQ_R 0.00
param set-default CA_SV_CS2_TRQ_P 1.00
param set-default CA_SV_CS2_TRQ_Y 0.00
param set-default CA_SV_CS3_TYPE 3
param set-default CA_SV_CS3_TRQ_R 0.00
param set-default CA_SV_CS3_TRQ_P 0.00
param set-default CA_SV_CS3_TRQ_Y 1.00

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

